name: pincher build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: update
      run: sudo apt-get update
    - name: install packages
      run: sudo apt-get install vulkan-tools libvulkan-dev vulkan-validationlayers-dev libglfw3-dev libglm-dev
    - name: build project
      run: make
